# fly.toml file for escape-bot-app
app = "escape-bot-app"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "escape_data"
  destination = "/app/User"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"