name: Fly Deploy

on:
  workflow_dispatch:
    inputs:
      perform-deploy:
        required: true
        type: boolean

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: escape-bot-24-7
    if: ${{ inputs.perform-deploy }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
